// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package model

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/gofrs/uuid"
)

// Defines values for ModelDefinitionStatus.
const (
	ModelDefinitionStatusDuplicate ModelDefinitionStatus = "duplicate"
	ModelDefinitionStatusEnabled   ModelDefinitionStatus = "enabled"
	ModelDefinitionStatusIgnored   ModelDefinitionStatus = "ignored"
)

// Defines values for ModelDefinitionRegistrantStatus.
const (
	ModelDefinitionRegistrantStatusConnected    ModelDefinitionRegistrantStatus = "connected"
	ModelDefinitionRegistrantStatusDeleted      ModelDefinitionRegistrantStatus = "deleted"
	ModelDefinitionRegistrantStatusDisconnected ModelDefinitionRegistrantStatus = "disconnected"
	ModelDefinitionRegistrantStatusDiscovered   ModelDefinitionRegistrantStatus = "discovered"
	ModelDefinitionRegistrantStatusIgnored      ModelDefinitionRegistrantStatus = "ignored"
	ModelDefinitionRegistrantStatusMaintenance  ModelDefinitionRegistrantStatus = "maintenance"
	ModelDefinitionRegistrantStatusNotFound     ModelDefinitionRegistrantStatus = "not found"
	ModelDefinitionRegistrantStatusRegistered   ModelDefinitionRegistrantStatus = "registered"
)

// Defines values for ModelDefinitionMetadataCapabilitiesEntityState.
const (
	Declaration ModelDefinitionMetadataCapabilitiesEntityState = "declaration"
	Instance    ModelDefinitionMetadataCapabilitiesEntityState = "instance"
)

// Defines values for ModelDefinitionMetadataCapabilitiesStatus.
const (
	Disabled ModelDefinitionMetadataCapabilitiesStatus = "disabled"
	Enabled  ModelDefinitionMetadataCapabilitiesStatus = "enabled"
)

// ModelDefinition Meshery Models serve as a portable unit of packaging to define managed entities, their relationships, and capabilities.
type ModelDefinition struct {
	// Id Uniquely identifies the entity (i.e. component) as defined in a declaration (i.e. design).
	Id *uuid.UUID `json:"id" yaml:"id"`

	// SchemaVersion Specifies the version of the schema used for the definition.
	SchemaVersion *string `json:"schemaVersion" yaml:"schemaVersion"`

	// Version Version of the model definition.
	Version string `json:"version" yaml:"version"`

	// Name The unique name for the model within the scope of a registrant.
	Name string `json:"name" yaml:"name"`

	// DisplayName Human-readable name for the model.
	DisplayName *string `json:"displayName" yaml:"displayName"`

	// Description Description of the model.
	Description *string `json:"description" yaml:"description"`

	// Status Status of model, including:
	// - duplicate: this component is a duplicate of another. The component that is to be the canonical reference and that is duplicated by other components should not be assigned the 'duplicate' status.
	// - maintenance: model is unavailable for a period of time.
	// - enabled: model is available for use for all users of this Meshery Server.
	// - ignored: model is unavailable for use for all users of this Meshery Server.
	Status *ModelDefinitionStatus `json:"status" yaml:"status"`

	// Registrant Meshery Connections are managed and unmanaged resources that either through discovery or manual entry are tracked by Meshery. Learn more at https://docs.meshery.io/concepts/logical/connections
	Registrant struct {
		// Id ID
		Id *uuid.UUID `json:"id" yaml:"id"`

		// Name Connection Name
		Name *string `db:"name" json:"name" yaml:"name"`

		// CredentialId Credential ID
		CredentialId *uuid.UUID `db:"credential_id" json:"credential_id" yaml:"credential_id"`

		// Type Connection Type
		Type string `db:"type" json:"type" yaml:"type"`

		// SubType Connection Subtype
		SubType *string `db:"sub_type" json:"sub_type" yaml:"sub_type"`

		// Kind Connection Kind
		Kind     string                  `db:"kind" json:"kind" yaml:"kind"`
		Metadata *map[string]interface{} `db:"metadata" json:"metadata" yaml:"metadata"`

		// Status Connection Status
		Status ModelDefinitionRegistrantStatus `db:"status" json:"status" yaml:"status"`

		// UserID A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
		UserID    *uuid.UUID `json:"user_id" yaml:"user_id"`
		CreatedAt time.Time  `json:"created_at" yaml:"created_at"`
		UpdatedAt time.Time  `json:"updated_at" yaml:"updated_at"`
		DeletedAt time.Time  `json:"deleted_at" yaml:"deleted_at"`
	} `gorm:"foreignKey:RegistrantId;references:Id" json:"registrant" yaml:"registrant"`

	// Category Category of the model.
	Category struct {
		// Id A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
		Id       *uuid.UUID              `json:"id" yaml:"id"`
		Name     *string                 `json:"name" yaml:"name"`
		Metadata *map[string]interface{} `json:"metadata" yaml:"metadata"`
	} `gorm:"foreignKey:CategoryId;references:Id" json:"category" yaml:"category"`

	// SubCategory Sub-category of the model.
	SubCategory *string `json:"subCategory" yaml:"subCategory"`

	// Metadata Metadata containing additional information associated with the model.
	Metadata *ModelDefinition_Metadata `gorm:"type:bytes;serializer:json" json:"metadata,omitempty"`

	// Model Registrant-defined data associated with the model. Properties pertain to the software being managed (e.g. Kubernetes v1.31)
	Model *struct {
		// Version Version of the model as defined by the registrant.
		Version string `json:"version" yaml:"version"`
	} `gorm:"type:bytes;serializer:json" json:"model,omitempty"`
}

// ModelDefinitionStatus Status of model, including:
// - duplicate: this component is a duplicate of another. The component that is to be the canonical reference and that is duplicated by other components should not be assigned the 'duplicate' status.
// - maintenance: model is unavailable for a period of time.
// - enabled: model is available for use for all users of this Meshery Server.
// - ignored: model is unavailable for use for all users of this Meshery Server.
type ModelDefinitionStatus string

// ModelDefinitionRegistrantStatus Connection Status
type ModelDefinitionRegistrantStatus string

// ModelDefinitionMetadataCapabilitiesEntityState A string starting with an alphanumeric character. Spaces and hyphens allowed.
type ModelDefinitionMetadataCapabilitiesEntityState string

// ModelDefinitionMetadataCapabilitiesStatus Status of the capability
type ModelDefinitionMetadataCapabilitiesStatus string

// ModelDefinition_Metadata Metadata containing additional information associated with the model.
type ModelDefinition_Metadata struct {
	// Capabilities Capabilities associated with the model
	Capabilities *[]struct {
		// SchemaVersion Specifies the version of the schema to which the capability definition conforms.
		SchemaVersion string `json:"schemaVersion" yaml:"schemaVersion"`

		// Version Version of the capability definition.
		Version string `json:"version" yaml:"version"`

		// DisplayName Name of the capability in human-readible format.
		DisplayName string `json:"displayName" yaml:"displayName"`

		// Description A written representation of the purpose and characteristics of the capability.
		Description *string `json:"description" yaml:"description"`

		// Kind Top-level categorization of the capability
		Kind string `json:"kind" yaml:"kind"`

		// Type Classification of capabilities. Used to group capabilities similar in nature.
		Type string `json:"type" yaml:"type"`

		// SubType Most granular unit of capability classification. The combination of Kind, Type and SubType together uniquely identify a Capability.
		SubType *string `json:"subType" yaml:"subType"`

		// Key Key that backs the capability.
		Key *string `json:"key" yaml:"key"`

		// EntityState State of the entity in which the capability is applicable.
		EntityState []ModelDefinitionMetadataCapabilitiesEntityState `json:"entityState"`

		// Status Status of the capability
		Status ModelDefinitionMetadataCapabilitiesStatus `json:"status" yaml:"status"`

		// Metadata Metadata contains additional information associated with the capability. Extension point.
		Metadata *map[string]interface{} `json:"metadata" yaml:"metadata"`
	} `json:"capabilities,omitempty"`

	// IsAnnotation Indicates whether the model and its entities should be treated as deployable entities or as logical representations.
	IsAnnotation *bool `json:"isAnnotation" yaml:"isAnnotation"`

	// PrimaryColor Primary color associated with the model.
	PrimaryColor *string `json:"primaryColor" yaml:"primaryColor"`

	// SecondaryColor Secondary color associated with the model.
	SecondaryColor *string `json:"secondaryColor" yaml:"secondaryColor"`

	// SvgWhite SVG representation of the model in white color.
	SvgWhite *string `json:"svgWhite" yaml:"svgWhite"`

	// SvgColor SVG representation of the model in colored format.
	SvgColor *string `json:"svgColor" yaml:"svgColor"`

	// SvgComplete SVG representation of the complete model.
	SvgComplete          *string                `json:"svgComplete" yaml:"svgComplete"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for ModelDefinition_Metadata. Returns the specified
// element and whether it was found
func (a ModelDefinition_Metadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ModelDefinition_Metadata
func (a *ModelDefinition_Metadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ModelDefinition_Metadata to handle AdditionalProperties
func (a *ModelDefinition_Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["capabilities"]; found {
		err = json.Unmarshal(raw, &a.Capabilities)
		if err != nil {
			return fmt.Errorf("error reading 'capabilities': %w", err)
		}
		delete(object, "capabilities")
	}

	if raw, found := object["isAnnotation"]; found {
		err = json.Unmarshal(raw, &a.IsAnnotation)
		if err != nil {
			return fmt.Errorf("error reading 'isAnnotation': %w", err)
		}
		delete(object, "isAnnotation")
	}

	if raw, found := object["primaryColor"]; found {
		err = json.Unmarshal(raw, &a.PrimaryColor)
		if err != nil {
			return fmt.Errorf("error reading 'primaryColor': %w", err)
		}
		delete(object, "primaryColor")
	}

	if raw, found := object["secondaryColor"]; found {
		err = json.Unmarshal(raw, &a.SecondaryColor)
		if err != nil {
			return fmt.Errorf("error reading 'secondaryColor': %w", err)
		}
		delete(object, "secondaryColor")
	}

	if raw, found := object["svgWhite"]; found {
		err = json.Unmarshal(raw, &a.SvgWhite)
		if err != nil {
			return fmt.Errorf("error reading 'svgWhite': %w", err)
		}
		delete(object, "svgWhite")
	}

	if raw, found := object["svgColor"]; found {
		err = json.Unmarshal(raw, &a.SvgColor)
		if err != nil {
			return fmt.Errorf("error reading 'svgColor': %w", err)
		}
		delete(object, "svgColor")
	}

	if raw, found := object["svgComplete"]; found {
		err = json.Unmarshal(raw, &a.SvgComplete)
		if err != nil {
			return fmt.Errorf("error reading 'svgComplete': %w", err)
		}
		delete(object, "svgComplete")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ModelDefinition_Metadata to handle AdditionalProperties
func (a ModelDefinition_Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Capabilities != nil {
		object["capabilities"], err = json.Marshal(a.Capabilities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'capabilities': %w", err)
		}
	}

	if a.IsAnnotation != nil {
		object["isAnnotation"], err = json.Marshal(a.IsAnnotation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isAnnotation': %w", err)
		}
	}

	if a.PrimaryColor != nil {
		object["primaryColor"], err = json.Marshal(a.PrimaryColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'primaryColor': %w", err)
		}
	}

	if a.SecondaryColor != nil {
		object["secondaryColor"], err = json.Marshal(a.SecondaryColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'secondaryColor': %w", err)
		}
	}

	if a.SvgWhite != nil {
		object["svgWhite"], err = json.Marshal(a.SvgWhite)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'svgWhite': %w", err)
		}
	}

	if a.SvgColor != nil {
		object["svgColor"], err = json.Marshal(a.SvgColor)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'svgColor': %w", err)
		}
	}

	if a.SvgComplete != nil {
		object["svgComplete"], err = json.Marshal(a.SvgComplete)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'svgComplete': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
